// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNfgg8-IrW12czk0pDWQ-JXonWzG17Lyw',
    appId: '1:635155211821:web:0920d1695d7dd05ce27aa4',
    messagingSenderId: '635155211821',
    projectId: 'pappa-connect',
    authDomain: 'pappa-connect.firebaseapp.com',
    storageBucket: 'pappa-connect.appspot.com',
    measurementId: 'G-CJLX6J22KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwBaU3OCrYtrTkWWvSSBqgP3BSXJNRuLU',
    appId: '1:635155211821:android:1156e72a447da704e27aa4',
    messagingSenderId: '635155211821',
    projectId: 'pappa-connect',
    storageBucket: 'pappa-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKZ-CENPeXVno3oC3zt5xkHo8pBx7gFk',
    appId: '1:635155211821:ios:d94d960911a33d5ce27aa4',
    messagingSenderId: '635155211821',
    projectId: 'pappa-connect',
    storageBucket: 'pappa-connect.appspot.com',
    iosBundleId: 'com.pappaconnect.pappaConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBKZ-CENPeXVno3oC3zt5xkHo8pBx7gFk',
    appId: '1:635155211821:ios:d94d960911a33d5ce27aa4',
    messagingSenderId: '635155211821',
    projectId: 'pappa-connect',
    storageBucket: 'pappa-connect.appspot.com',
    iosBundleId: 'com.pappaconnect.pappaConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNfgg8-IrW12czk0pDWQ-JXonWzG17Lyw',
    appId: '1:635155211821:web:8634e7d29748b408e27aa4',
    messagingSenderId: '635155211821',
    projectId: 'pappa-connect',
    authDomain: 'pappa-connect.firebaseapp.com',
    storageBucket: 'pappa-connect.appspot.com',
    measurementId: 'G-2WX3M82338',
  );
}
